# Generated by Django 4.1 on 2022-08-27 15:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_employee_team_delete_ticket_client_company_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="company_name",
            field=models.CharField(default=" ", max_length=250),
        ),
        migrations.AddField(
            model_name="client",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 8, 27, 17, 10, 55, 934585)
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="date_update",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 8, 27, 17, 10, 55, 934585)
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="email",
            field=models.CharField(default=" ", max_length=100),
        ),
        migrations.AddField(
            model_name="client",
            name="employee_contact",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="crm.employee",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="first_name",
            field=models.CharField(default=" ", max_length=25),
        ),
        migrations.AddField(
            model_name="client",
            name="last_name",
            field=models.CharField(default=" ", max_length=25),
        ),
        migrations.AddField(
            model_name="client",
            name="mobile",
            field=models.CharField(default=" ", max_length=20),
        ),
        migrations.AddField(
            model_name="client",
            name="phone",
            field=models.CharField(default=" ", max_length=20),
        ),
        migrations.AddField(
            model_name="contract",
            name="amount",
            field=models.FloatField(default=10.2),
        ),
        migrations.AddField(
            model_name="contract",
            name="client",
            field=models.OneToOneField(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="crm.client"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 8, 27, 17, 10, 55, 934585)
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="date_update",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 8, 27, 17, 10, 55, 934585)
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="employee_contact",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="crm.employee",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="payment_due",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 8, 27, 17, 10, 55, 934585)
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employee",
            name="team",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="crm.team"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="attendees",
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name="event",
            name="client",
            field=models.OneToOneField(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="crm.client"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 8, 27, 17, 10, 55, 934585)
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="date_update",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 8, 27, 17, 10, 55, 934585)
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="employee_contact",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales_contact",
                to="crm.employee",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="employee_event",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_contact",
                to="crm.employee",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="event_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 8, 27, 17, 10, 55, 934585)
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="notes",
            field=models.TextField(blank=True, max_length=8192),
        ),
        migrations.AlterField(
            model_name="employee",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 8, 27, 17, 10, 55, 934585)
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="date_update",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 8, 27, 17, 10, 55, 934585)
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.CharField(default=" ", max_length=100),
        ),
        migrations.AlterField(
            model_name="employee",
            name="first_name",
            field=models.CharField(default=" ", max_length=25),
        ),
        migrations.AlterField(
            model_name="employee",
            name="last_name",
            field=models.CharField(default=" ", max_length=25),
        ),
        migrations.AlterField(
            model_name="employee",
            name="mobile",
            field=models.CharField(default=" ", max_length=20),
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone",
            field=models.CharField(default=" ", max_length=20),
        ),
    ]
