# Generated by Django 4.1 on 2022-08-28 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_alter_client_date_created_alter_client_date_update_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="statuts_client",
            field=models.CharField(default=" ", max_length=25),
        ),
        migrations.AlterField(
            model_name="client",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 8, 28, 15, 6, 9, 452399)
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="date_update",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 8, 28, 15, 6, 9, 452399)
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 8, 28, 15, 6, 9, 453399)
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="date_update",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 8, 28, 15, 6, 9, 453399)
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="payment_due",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 8, 28, 15, 6, 9, 453399)
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 8, 28, 15, 6, 9, 451400)
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="date_update",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 8, 28, 15, 6, 9, 451400)
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 8, 28, 15, 6, 9, 454400)
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date_update",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 8, 28, 15, 6, 9, 454400)
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 8, 28, 15, 6, 9, 454400)
            ),
        ),
    ]
