# Generated by Django 4.1 on 2022-08-30 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0012_alter_contract_date_created_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="client",
        ),
        migrations.AddField(
            model_name="event",
            name="contract",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event",
                to="crm.contract",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="employee_contact",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="sales_contact",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="employee_event",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="event_contact",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
