# Generated by Django 4.1 on 2022-08-30 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0015_alter_client_employee_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="employee_contact",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
