# Generated by Django 4.1 on 2022-08-30 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0016_alter_contract_employee_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="employee_contact",
        ),
    ]
