# Generated by Django 4.1 on 2022-08-30 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0017_remove_event_employee_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="employee_contact",
        ),
    ]
