# Generated by Django 4.1 on 2022-08-30 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0019_client_employee_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="client",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_event",
                to="crm.client",
            ),
            preserve_default=False,
        ),
    ]
