# Generated by Django 4.1 on 2022-08-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0020_event_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="is_staff",
            field=models.BooleanField(default=True),
        ),
    ]
