# Generated by Django 4.1 on 2022-09-02 03:58

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("crm", "0021_alter_employee_is_staff"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event_status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EN PREPARATION", "EN PREPARATION"),
                            ("EN COURS", "EN COURS"),
                            ("TERMINE", "TERMINE"),
                        ],
                        default="EN PREPARATION",
                        max_length=128,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "group_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="auth.group",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("MANAGER", "MANAGER"),
                            ("COMMERCIAL", "COMMERCIAL"),
                            ("SUPPORT", "SUPPORT"),
                        ],
                        default="MANAGER",
                        max_length=128,
                    ),
                ),
            ],
            bases=("auth.group",),
            managers=[
                ("objects", django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.RenameField(
            model_name="contract",
            old_name="status",
            new_name="signed",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="role",
        ),
        migrations.RemoveField(
            model_name="event",
            name="client",
        ),
        migrations.AddField(
            model_name="contract",
            name="contract_name",
            field=models.CharField(default="test", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="event_status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_event",
                to="crm.client",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="employee",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site.",
                verbose_name="staff status",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="crm.team",
            ),
        ),
    ]
