# Generated by Django 4.1 on 2022-09-05 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=25)),
                ("last_name", models.CharField(blank=True, max_length=25)),
                ("email", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("mobile", models.CharField(blank=True, max_length=20)),
                ("company_name", models.CharField(blank=True, max_length=250)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
                (
                    "statuts_client",
                    models.CharField(
                        choices=[("POTENTIEL", "POTENTIEL"), ("EXISTANT", "EXISTANT")],
                        default="POTENTIEL",
                        max_length=25,
                    ),
                ),
                (
                    "employee_contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_name", models.CharField(max_length=128)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
                ("signed", models.BooleanField(default=False)),
                ("amount", models.FloatField()),
                ("payment_due", models.DateTimeField()),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract",
                        to="crm_api.client",
                    ),
                ),
                (
                    "employee_contact",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event_status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EN PREPARATION", "EN PREPARATION"),
                            ("EN COURS", "EN COURS"),
                            ("TERMINE", "TERMINE"),
                        ],
                        default="EN PREPARATION",
                        max_length=128,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
                ("event_date", models.DateTimeField()),
                ("notes", models.TextField(blank=True, max_length=8192)),
                ("attendees", models.IntegerField()),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event",
                        to="crm_api.contract",
                    ),
                ),
                (
                    "employee_event",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="event_contact",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_event",
                        to="crm_api.event_status",
                    ),
                ),
            ],
        ),
    ]
